/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entrega_introducao;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertEquals(1, 1);
    }
}
